/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <pthread.h>
#include <unistd.h>
#include <android/log.h>
#include <sys/system_properties.h>
#include <stdlib.h>
#include <fcntl.h>
#include <time.h>
#include <string>
#include <dlfcn.h>
#include <string.h>
#include "dlopen.h"
#include "util/deviceutils.h"
#include "util/fileutils.h"

#if defined(__aarch64__)

#include "And64InlineHook.hpp"

#elif defined(__arm__)
#include "inlineHook.h"
#endif

#ifndef _Included_com_salton123_hook_dex_NativeDump
#define _Included_com_salton123_hook_dex_NativeDump
#ifdef __cplusplus
extern "C" {

#endif
/*
 * Class:     com_salton123_hook_dex_NativeDump
 * Method:    dump
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_salton123_hook_dex_NativeDump_dump
        (JNIEnv *, jclass, jstring);


#ifdef __cplusplus
}
#endif
#endif
